# Generated by Django 5.2.17 on 2026-09-24 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_topic_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-date_added'], 'verbose_name': 'запись', 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['date_added'], 'verbose_name': 'тема', 'verbose_name_plural': 'темы'},
        ),
        migrations.AddField(
            model_name='entry',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='изменена'),
        ),
        migrations.AddField(
            model_name='topic',
            name='public',
            field=models.BooleanField(default=False, help_text='Открытую тему могут читать все посетители, но изменять - только вы.', verbose_name='открытая тема'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='добавлена'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(verbose_name='запись'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='learning_logs.topic', verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='создана'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, verbose_name='тема'),
        ),
    ]
